DROP TABLE IF EXISTS 'tag';
DROP TABLE IF EXISTS 'track';

CREATE TABLE 'tag' ( 'id' INTEGER PRIMARY KEY AUTOINCREMENT, 'tagname' VARCHAR(50), 'tagurl' VARCHAR(255) );
CREATE TABLE 'track' ( 'id' INTEGER PRIMARY KEY AUTOINCREMENT, 'trackname' VARCHAR(50), 'trackurl' VARCHAR(255) );