DROP TABLE IF EXISTS tag;
DROP TABLE IF EXISTS track;
DROP TABLE IF EXISTS album;
DROP TABLE IF EXISTS artist;
--tag=genre
CREATE TABLE tag ( id INTEGER PRIMARY KEY AUTOINCREMENT, tagname VARCHAR(50), tagurl VARCHAR(255) );
CREATE TABLE track ( id INTEGER PRIMARY KEY AUTOINCREMENT, trackname VARCHAR(50), trackurl VARCHAR(255) );
CREATE TABLE album ( id INTEGER PRIMARY KEY AUTOINCREMENT, albumname VARCHAR(50), albumurl VARCHAR(255) );
CREATE TABLE artist ( id INTEGER PRIMARY KEY AUTOINCREMENT, artistname VARCHAR(50), artisturl VARCHAR(255) );